### ISSUE TITLE
Radiobutton click delay

### ISSUE THREAD

**Issue by chestozo** [yandex-ui/stylobate-islands#12]
http://yandex-ui.github.io/stylobate-islands/skins/#skin-islands-button_checked
When clicking on radiobutton buttons there is a notable delay.

**Comment by chestozo** [comment]
js button looks faster than css button, based on checkbox IMHO

**Comment by kizu** [comment]
Well, I think that's just how browsers work with HTML&CSS way of doing this stuff (there could be a delay for triggering `:checked`, who knows). But if you'd research this stuff and would find a way to make all those stuff faster without using JS — it would be nice and you can either show me some examples, or send PRs :)

Anyway I'll close this issue: if someone would want the fastest buttons, they could use JS variant (and that's why we have it in an example), and if the slower one, but on CSS, would be ok them — well, ok.

**Comment by chestozo** [comment]
Maybe this is visible on such a big page with many elements and also maybe it is caused by a selector speed.
Will try to give a look at this later )
Thank you!
